# Generated by Django 4.2.11 on 2024-05-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_managers_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(default='!IlvtlhOgxeaSjiGAKG1Rit8GNZwOG0iSTP9sssXh', max_length=128),
        ),
    ]
