# Generated by Django 4.2.11 on 2024-05-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(default='!2bTRKq8vPrLnXnvKsZwGapulqKwq6Z69bHf1IIu5', max_length=128),
        ),
    ]
