# Generated by Django 4.2.11 on 2024-05-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(default='!A4jEzMvKiwPijY9zMEKQuVousJneovesIh0bvEAZ', max_length=128),
        ),
    ]
